CXX := /home/farabi/gcc-11.2.0-build/bin/g++
SRCS := multithreaded-l2-latency


multi: 
	$(CXX)  -o  $(SRCS).out $(SRCS).cpp -L/home/farabi/gcc-11.2.0-build/lib64/libstdc++.so.6 -lpthread ; 

clean:
	rm -rf *.out 
